kind = "web"
previewPath = "/"
title = "GhostProtocol dApp"
version = "1.0.0"
id = "artifacts/ghost-protocol"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18374

[services.development]
run = "pnpm --filter @workspace/ghost-protocol run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ghost-protocol", "run", "build" ]
publicDir = "artifacts/ghost-protocol/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18374"
BASE_PATH = "/"
